# Generated by Django 5.2 on 2025-04-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('experiencia', models.TextField()),
                ('formacao', models.TextField()),
                ('pontuacao', models.FloatField()),
                ('vaga', models.CharField(max_length=100)),
            ],
        ),
    ]
